# Generated by Django 5.2.1 on 2025-05-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='status',
            field=models.CharField(choices=[('Pending Validation', 'Pending Validation'), ('Validated', 'Validated'), ('Billed Back', 'Billed Back'), ('Recovered', 'Recovered')], default='Pending Validation', max_length=50),
        ),
    ]
