# Generated by Django 5.2.1 on 2025-05-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osd', '0002_workflow_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='date_worked',
            field=models.DateField(blank=True, null=True),
        ),
    ]
