# Generated by Django 5.2.1 on 2025-06-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osd', '0003_workflow_date_worked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deductions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deduction_reference', models.CharField(max_length=255, unique=True)),
                ('standard_customer', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(max_length=255)),
                ('deducted_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deduction_date', models.DateField()),
                ('deduction_reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending Validation', 'Pending Validation'), ('Validated', 'Validated'), ('Billed Back', 'Billed Back'), ('Recovered', 'Recovered')], default='Pending Validation', max_length=50)),
                ('validation_status', models.CharField(choices=[('Valid', 'Valid'), ('Invalid', 'Invalid'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('valid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('invalid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_worked', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Deduction',
                'verbose_name_plural': 'Deductions',
                'ordering': ['-deduction_date'],
            },
        ),
    ]
