# Generated by Django 5.2.1 on 2025-06-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osd', '0004_deductions'),
    ]

    operations = [
        migrations.AddField(
            model_name='deductions',
            name='open_closed',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10),
        ),
    ]
