# Generated by Django 5.2.1 on 2025-06-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osd', '0005_deductions_open_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='deductions',
            name='tolerance',
            field=models.CharField(blank=True, choices=[('UT', 'Under Tolerance'), ('OT', 'Over Tolerance')], max_length=2, null=True),
        ),
    ]
