# Generated by Django 5.2.1 on 2025-06-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osd', '0006_deductions_tolerance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deductions',
            name='deduction_reference',
            field=models.CharField(max_length=255),
        ),
    ]
