# Generated by Django 5.2.1 on 2025-06-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osd', '0007_alter_deductions_deduction_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=255, unique=True)),
                ('invoice_date', models.DateField()),
                ('billed_qty', models.IntegerField()),
                ('sku', models.CharField(max_length=100)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_number', models.CharField(max_length=100)),
                ('bol', models.CharField(max_length=100, verbose_name='Bill of Lading')),
                ('carrier', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-invoice_date'],
            },
        ),
    ]
