# Generated by Django 5.2.1 on 2025-06-13 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osd', '0009_alter_invoice_options_alter_invoice_invoice_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='standard_customer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
