# Generated by Django 5.2.1 on 2025-06-13 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osd', '0010_invoice_standard_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='standard_customer',
        ),
        migrations.AddField(
            model_name='deductions',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osd.invoice', to_field='invoice_number'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
