# Generated by Django 5.2.1 on 2025-06-13 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osd', '0011_remove_invoice_standard_customer_deductions_invoice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deductions',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osd.invoice'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(max_length=255),
        ),
    ]
