# Generated by Django 5.2.1 on 2025-06-13 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osd', '0012_alter_deductions_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='standard_customer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
