# Generated by Django 5.2.1 on 2025-06-16 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('osd', '0013_invoice_standard_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='deductions',
            name='recovered_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
